config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
    namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/welcome', to: 'base#welcome'
      resources :products
    end
  end
  get '/home', to: 'pages#home', defaults: { format: :html }
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API

  # after_action :verify_authorized, except: :index
  # after_action :verify_policy_scoped, only: :index

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def welcome
    render json: {
      message: "Ruby on Rails Challenge 20200810"
    }, status: :ok
  end

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::BaseController
  before_action :load_product, except: [:index, :new, :create, :banana]

  def index
    @products = Product.all
    render json: {
      products: @products
    }, status: :ok
  end

  def show
    render json: {
      products: @product
    }, status: :ok
  end

  def new
    @products = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      render json: {
        product: @products
      }, status: :ok
    else
      render json:{
        message: "Product creation failed",
        errors: @product.errors.full_messages
       }, status: :unprocessable_entity
    end
  end

  def edit
    @products = Product.find(params[:id])
  end

  def update
    if @product.update(product_params)
      render json: {
        product: @product
       }, status: :ok
    else
      render json:{
        message: "Product could not be updated",
        errors: @product.erros.full_messages
       }, status: :unprocessable_entity
    end
  end

  def destroy
    if @product.destroy
      render json:{
      message: "Product deleted",
      }, status: :ok
    else
      render json: {
        message: "Product could be not be deleted"
       }, status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :product_type, :price, :rating)
  end

  def load_product
    @product = Product.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :load_product

  def home
    @products = Product.all
  end

  def edit
    @products = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product), notice: 'Product updated successfully'
    else
      render :edit
    end
  end

  def create

  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to home_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :product_type, :price, :rating)
  end

  def load_product
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>TESTEAPI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<div class="container mt-3">
  <%= simple_form_for page_path do |f| %>
    <%= f.input :title, label: 'Title' %>
    <%= f.input :product_type, label: 'Type' %>
    <%= f.input :price, label: 'Price'%>
    <%= f.button :submit, "Send", class: "btn btn-primary btn-lg"%>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h2>Products</h2>
  <div class="row">
<div class="container">
  <%= form_tag pages_path do %>
    <label for="file">File to upload</label> <%= file_field_tag "file" %>
    <div><%= submit_tag 'Submit' %></div>
  <% end %>
    <table class="table_style">
        <tr>
          <th>Title</th>
          <th>Type</th>
          <th>Rating</th>
          <th>Price</th>
          <th>Created</th>
          <th>Action</th>
        </tr>
        <% @products.each do |product| %>
        <tr>
        <td><%= product.title %></td>
        <td><%= product.product_type %></td>
        <td><%= product.rating %></td>
        <td><%= product.price %></td>
        <td><%= product.created_at %></td>
        <td><%= link_to "Edit", edit_page_path(product.id) %> <%= link_to "Delete", page_path(product.id), method: :delete %></td>
        <% end %>
    </table>
  </div>
</div>
</div>